os: linux
dist: bionic
language: generic
sudo: required

git:
  depth: 1

addons:
  apt:
    update: true

services:
  - docker

before_install:
  - docker pull fr3akyphantom/droid-builder:latest

before_script:
  - cd $HOME && mkdir twrp
  - git clone -b android-13.0 https://github.com/TeamWin/android_device_twrp.git twrp
  - cd $HOME/twrp/ && git clone https://github.com/juuanj/TWRP-POCO-C65-Redmi-13C-Gale.git device/xiaomi/gale

script:
  - cd $HOME/twrp
  - source build/envsetup.sh
  - lunch omni_gale-eng
  - mka recoveryimage

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: juuanj/TWRP-POCO-C65-Redmi-13C-Gale
    branch: main

branches:
  only:
    - android-13.0
    - main

env:
  global:
    - ANDROID_SDK_ROOT=/opt/sdk
    - PATH="${ANDROID_SDK_ROOT}/emulator:${ANDROID_SDK_ROOT}/tools:${ANDROID_SDK_ROOT}/tools/bin:${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
